"""
# A simple streamlit app to visualize the category and backlink data generated by the rekt_summarizer project
"""

import streamlit as st
import pickle

DATA_DIRECTORY = "rekt_summarizer/data"

# e.g: 
# categories_and_backlinks = {
#   'categories': {
#     'contract_manipulation': 75,
#     'reentrancy_attack': 30,
#   },
#   'backlinks': {
#     'contract_manipulation': ["https://rekt.news/merlin3-rekt/", "https://rekt.news/beanstalk-rekt/"],
#     'human_error': ["https://rekt.news/ronin-rekt/", "https://rekt.news/beanstalk-rekt/"], "rugpull": ["https://rekt.news/ronin-rekt/"]
#   }
# }

categories_and_backlinks = {}
with open(f"{DATA_DIRECTORY}/summarization_results.pkl", 'rb') as file:
    categories_and_backlinks = pickle.load(file)

st.title('rekt.news Leaderboard hack count by category')

st.bar_chart(categories_and_backlinks["categories"])

if st.checkbox('Show raw category data'):
    st.subheader('categories')
    st.write(categories_and_backlinks["categories"])

if st.checkbox('Show raw backlink data'):
    st.subheader('backlinks')
    st.write(categories_and_backlinks["backlinks"])